### ISSUE TITLE
zsh completing descriptions as well

### ISSUE THREAD

**Issue by willsALMANJ** [Schnouki/git-annex-zsh-completion#7]
I am experiencing a strange issue trying to use the completion function. When I hit tab, zsh uses both the git-annex commands and their descriptions as possible completions. So `git-annex sy<Tab>` gives

    check for data that has no symlinks pointing to it           fixes up symlinks that are staged as part of a commit        sync
    fix up symlinks that have become broken                      like watch but automatically syncs changes to other remotes  synchronize with one or more remotes

as the possible completions. I installed the function using the suggested method: added its directory to `fpath` and then did `compinit git-annex`. Any idea what could be going on? My only guess is that my version of zsh is kind of old (4.3.10). Does this function use some syntax that was recently added to zsh?

**Comment by willsALMANJ** [comment]
I tried the using the completion function the same way on a newer version of zsh (5.0.7) and saw the same behavior. Am I not loading the function properly?

**Comment by dfaligertwood** [comment]
I'm also having this issue.

**Comment by dfaligertwood** [comment]
Problem was introduced by commit e2b78c6

**Comment by dfaligertwood** [comment]
Reverting these changes seems to fix this.

**Comment by willsALMANJ** [comment]
Maybe @ypid can comment on why that commit had these side effects?

**Comment by dfaligertwood** [comment]
Eyeballing it it looks like it was for code clarity. I've submitted a pull request that fixes the bug anyway.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: willsALMANJSent: Saturday, 8 August 2015 12:11To: Schnouki/git-annex-zsh-completionReply To: Schnouki/git-annex-zsh-completionCc: dfaligertwoodSubject: Re: [git-annex-zsh-completion] zsh completing descriptions as well (#7)Maybe @ypid can comment on why that commit had these side effects?

—Reply to this email directly or view it on GitHub.

**Comment by ypid** [comment]
I did not know that this change had this unintended side effect. Sorry for the inconvenience … The patch from @dfaligertwood fixes it.

**Comment by willsALMANJ** [comment]
No problem. I was just checking to make sure we weren't missing something.

**Comment by Schnouki** [comment]
Merged. Thanks to all of you guys for the bug report and the fix! :smile:
